backend:
  name: github
  repo: guilhermejcgois/website
  branch: main
  squash_merges: true
  open_authoring: true

publish_mode: editorial_workflow
media_folder: public/images
public_folder: /images
site_url: https://gois-dev.netlify.app/" # your site name

i18n:
  structure: multiple_files
  locales: [pt, en]

collections:
  - name: post
    label: Posts
    folder: src/content/posts
    create: true
    format: frontmatter
    preview_path: post/{{slug}}
    i18n: true
    fields:
      - label: Title
        name: title
      - label: Description
        name: description
      - label: Date
        name: publishedAt
        widget: date
      - label: Publish
        name: isPublish
        widget: boolean
        default: true
      - label: Draft
        name: isDraft
        widget: boolean
        default: false
      - label: Body
        name: body
        widget: markdown
